### ISSUE TITLE
Remove Path variable from SecretConfig

### ISSUE THREAD

**Issue by difince** [edgexfoundry/go-mod-secrets#26]
My suggestion is Path variable to be removed from the SecretConfig struct
https://github.com/edgexfoundry/go-mod-secrets/blob/56ee9b8d141cb880873bb703d8068ae07117a8d0/pkg/providers/vault/config.go#L21-L29
So, when the clients want to read secrets, first the path should be specified and then the keys.
Thus, with only a single instance of  SecretConfig, the client will be able to read secrets from different paths.

**Comment by AnthonyMBonafide** [comment]
I think this is a great idea, @tingyuz / @mkbhanda  is this something we will need to implement sooner rather than later? I ask because we are starting the integration process for the core-services and I am wondering if how we are storing secrets in vault will require this functionality or if a services secrets will always be at one location(path).

**Comment by mkbhanda** [comment]
@AnthonyMBonafide The way I understood Vault documentation is there are policies and users have policies associated with them. The user supplies their token and inside Vault it gets mapped to associated policies which then gets digests to ACLs. So if we provide a path and that does not map to a path with access per policy, its a no-op. So I agree with @difince in no need to specify path in Secret Config, but if those policies are specified right, even if you specify a path, it should not be accessible. See https://www.vaultproject.io/docs/internals/security.html  

"On each request a client provides this token. Vault then uses it to check that the token is valid and has not been revoked or expired, and generates an ACL based on the associated policies. Vault uses a strict default deny or whitelist enforcement. This means unless an associated policy allows for a given action, it will be denied. Each policy specifies a level of access granted to a path in Vault. When the policies are merged (if multiple policies are associated with a client), the highest access level permitted is used. For example, if the "engineering" policy permits read/update access to the "eng/" path, and the "ops" policy permits read access to the "ops/" path, then the user gets the union of those. Policy is matched using the most specific defined policy, which may be an exact match or the longest-prefix match glob pattern."

Each of our services should have an associated policy specifying a path where their secrets will be stored. @tingyu do we define service-based policies? I know we have spoken of paths per service.

**Comment by tingyuz** [comment]
@mkbhanda The service-based policy will be defined with the token, and token is associated with path. 
If we move the path from the struct, it has to be defined somewhere else, or passed as a parameter, and the consumer of the go-mod-secret (other micro service ) will be responsible to retrieve such information somewhere. If we agree secretConfig contains all the secret related information, it makes sense to have them in a same place IMO.

**Comment by mkbhanda** [comment]
Each token has a source path used for revocation. see https://www.vaultproject.io/docs/internals/token.html

"Each token maintains the source path, or the login path, that was used to create the token. This is used to allow source based revocation. For example, if we believe our GitHub organization was compromised, we may want to revoke all tokens generated via auth/github/login. This would be done by using the sys/revoke-prefix/ API with the auth/github/ prefix. Revoking the prefix will revoke all client tokens generated at that path, as well as all dynamic secrets generated by those tokens. This provides a powerful "break glass" procedure during a potential compromise."

**Comment by bnevis-i** [comment]
Forward looking the [file-token-provider](https://github.com/edgexfoundry/edgex-docs/blob/master/security/security-file-token-provider.1.rst) will add metadata to the vault tokens `edgex-service-name` such that the go-mod-secrets can automatically build the `secret/edgex/_nameoftheservice_` path on the client's behalf.  The client still needs to indicate what secrets under that path they need to get.

**Comment by bnevis-i** [comment]
> Each token maintains the source path, or the login path, that was used to create the token. 

This is unrelated to the token policy that is attached to generated tokens.  All of the tokens that EdgeX generates are generated off of the `auth/token` path.  Something like `auth/github/login` is used for identity federation, where you have an external identity provider (like GitHub) and Vault delegates to that identity provider to authorize the creation of Vault tokens.  In EdgeX, we use Vault tokens to generate Vault tokens, where the chain of trust starts with the Vault root token.

**Comment by mkbhanda** [comment]
@bnevis-i , yes, token source path is different from policy. But  @difince question is can she toss out the path variable from secretConfig. My thinking is "no" if we need to capture it for things like token revocation

**Comment by bnevis-i** [comment]
> @bnevis-i , yes, token source path is different from policy. But @difince question is can she toss out the path variable from secretConfig. My thinking is "no" if we need to capture it for things like token revocation

This PR is not about removing Path, but rather it is about allowing clients to specify arbitrary paths to read secrets from.  As the code is currently written, the `Path` is used to build the URL for `getAllKeys()`  and all further secrets exposed by the API are scoped to that subtree.

I am OK with widening the interface such that the client can configure an arbitrary subtree to read secrets from in code, and may be ok with a method to read a single secret from an arbitrary path, but to compensate for the decline in usability we should add a method to retrieve the default subtree so that one could write

```
secretclient.SetSubtree(secretclient.DefaultSubtree())
```

I think that DefaultSubtree() should just return `SecretConfig.Path` for now, and use the previously describe autoconfig algorithm in the future when we move to per-service secrets.

So my counterproposal is:

- Keep SecretConfig.Path for now
- Make its use optional

**Comment by difince** [comment]
I am sorry, if I have written the issue ambiguously.
@bnevis-i  got my idea -  I just want to make the interface widen, by removing this "path" from the SecretConfig and move it to be param to GetValues method. Thus,

> it is about allowing clients to specify arbitrary paths to read secrets from

> with only a single instance of SecretConfig, the client will be able to read secrets from different paths.

**Comment by bnevis-i** [comment]
@difince  What do you propose the new interface should look like?

**Comment by AnthonyMBonafide** [comment]
I think that we also need to define how we are storing secrets in vault. We can store secrets for each service under one path, or have one secret per path. What is the general consensus as to how the secrets will live within Vault.

**Comment by mkbhanda** [comment]
Sorry @difince and @bnevis-i for mixing up other "path" references in this PR, path definitely is an overloaded term.
@AnthonyMBonafide I am inclined to paths that are service specific .. /core, ../meta-data, along the lines of unix /home/difince, /home/bnevis to restrict access to the path to the service that owns those secrets.

**Comment by AnthonyMBonafide** [comment]
@mkbhanda , I agree and like that approach. Would all the secrets for the particular service reside under that path. For example, would `../core-data` contain secrets for Mongo username, Mongo password, and other secrets unrelated to database?

**Comment by mkbhanda** [comment]
Yes @AnthonyMBonafide, that's how I would like it. @tingyuz also aligned on that.

**Comment by tingyuz** [comment]
@difince @AnthonyMBonafide I have received question regarding single instance of secretConfig - what is the major benefit VS. each microservice has it's own instance of secretConfig? We can justify the approach if this is addressed.

**Comment by bnevis-i** [comment]
For clarity, here is what is being implemented in https://github.com/edgexfoundry/edgex-go/pull/1792:

Each service gets a Vault token with meta "edgex-service-name" containing the name of the service.
This token can access (/v1?) `secret/edgex/` + (the value of above) + `/` + (name of the secret).  Each secret maps to a hash of key-value pairs, which are arbitrary.  (e.g. the Kong TLS secrets has both the private key and the certificate as key-value pairs).  There is also a capability to add arbitrary custom paths to the token's ACL that differ from the above pattern.  Let me know if any changes are needed.

**Comment by tingyuz** [comment]
@bnevis-i Just want to clarify in the example you have above - 
If we are request /v1/secret/edgex/{edegex-service-name} with the token but without the last part of (name of the secret), is the request going to be granted or denied?

**Comment by bnevis-i** [comment]
In the current PR, you have enumeration capability in addition to get and set:  If you created a secret at `/v1/secret/edgex/myservice/sample1` you could LIST `/v1/secret/edgex/myservice` and it will tell you `sample1` exists.  i.e. it would be granted.

**Comment by difince** [comment]
> @difince What do you propose the new interface should look like?

```
type SecretStoreManager interface {
	GetValues(path string ,keys ...string) (map[string]string, error)
}

```
```
type SecretConfig struct {
	Host           string
	Port           int
	### Path           string -> to be removed
	Protocol       string
	Namespace      string
	RootCaCert     string
	ServerName     string
	Authentication AuthenticationInfo
}
```
@tingyuz  How I have reached to this idea - I was implementing docker-edgex-mongo,that is responsible for setting up the mongo db for all the microservices. Currently we have 10 databases. For each one docker-edgex-mongo need to setup the db credentials, create the database with the respective collections inside, but firstly it needs to read the credentials from vault. So, I ended up with a loop that creates 10  SecretConfig instances. 
```
> show databases
admin                0.000GB
application-service  0.000GB
config               0.000GB
coredata             0.028GB
exportclient         0.000GB
local                0.000GB
logging              0.021GB
metadata             0.001GB
notifications        0.000GB
scheduler            0.000GB
```
From edgex-go microservices point of view at this stage, this change will be irrelevant - but I was thinking that in the future we could have a case when a microservice will need to read secrets from different paths. 
However, this was just a proposal. I am Ok if we stay with the current implementation. :) 

Currently, in edgex-mongo the path I am using is "/v1/secret/edgex/dbcredentials/{service-name}" - it looks I will need to remove "dbcredentials" and probably additional change will be needed in order to meet: 

> Each service gets a Vault token with meta "edgex-service-name" containing the name of the service.
This token can access (/v1?) secret/edgex/ + (the value of above) + / + (name of the secret), in the URL space of the secret store. 

This is still unclear to me, I need to take a closer look at that @bnevis-i have been implemented

**Comment by mkbhanda** [comment]
Thank you @difince for explaining your use case. It is a special case because it runs across all services. The way I see the path is for setting the longest common prefix, like a shortcut to reduce some typing. In your example of MongoDB it would be "/v1/secret/edgex/dbcredentials/" and then each of the service keys that you need to read would be
"<service-name>"/username, "<service-name>"/password etc.
So your for-loop would cycle through different service names but could use the same secrets client and append the service-name to the key. Path plus key leads to the absolute path to the key.
Typically within other services they should seek only their service specific keys and the auth token would further be used to check they have access to those secrets using the secret path.

**Comment by bnevis-i** [comment]
> Currently, in edgex-mongo the path I am using is "/v1/secret/edgex/dbcredentials/{service-name}" - it looks I will need to remove "dbcredentials" and probably additional change will be needed in order to meet:

I would invert that and store them at
`/v1/secret/edgex/{service-name}/dbcredentials`

and give your service an additional special-case cross-cutting ability to read/write
`/v1/secret/edgex/*/dbcredentials`
so that each service can pick up its respective credential from its own area.

I think your service also needs a special superuser credential for its own use, correct?

**Comment by AnthonyMBonafide** [comment]
I talked with @tingyuz, and we came to the conclusion that since the secrets in Vault will be organized in a way that the paths will differ depending on the category of data --for example `/v1/secret/edgex/core-data/mongodb` vs `/v1/secret/edgex/core-data/redisdb` each containing the secrets `username` and `password`-- it would be best if we retain the `path` configuration property which can be used to provide a base path such-as `/v1/secret/edgex/core-data` and the `SecretClient` can be updated to accept the specific path portion as well as the secret names, as @difince suggested:

```
type SecretStoreManager interface {
	GetValues(path string ,keys ...string) (map[string]string, error)
}
```

The user can then obtain database credentials with either of the following:

```
secretClient.GetValues("mongodb","username,"password")
```

or for Redis:

```
secretClient.GetValues("redisdb","username,"password")
```

The `SecretClient` would append the path to the base path in the `SecretConfig`(TOML). This approach would make using the client a bit easier as it is not assuming the secret structure layout. Also, we can make the retrieval of secrets common within EdgeX, for example all of the core service can obtain the username and password with the same call:

```
secretClient.GetValues("mongodb","username,"password")
```

since the base path is driven by configuration each service can then specify their own specific base path and the retrieval of secrets should work if our secrets are laid out consistently for each service. 


If this sounds reasonable and we all agree to the approach I would like to start working on this.

**Comment by bnevis-i** [comment]
@AnthonyMBonafide  You mean?

Given

-  `/v1/secret/edgex/core-data/redisdb` is a map
- `GetValues(path string ,keys ...string)` returns `(map[string]string, error)`

Then
`secretClient.GetValues("redisdb","username,"password")`
is asking that regardless of the keys stored in the map, that you only want the `username` and `password` keys returned?

**Comment by AnthonyMBonafide** [comment]
> @AnthonyMBonafide You mean?
> 
> Given
> 
> * `/v1/secret/edgex/core-data/redisdb` is a map
> * `GetValues(path string ,keys ...string)` returns `(map[string]string, error)`
> 
> Then
> `secretClient.GetValues("redisdb","username,"password")`
> is asking that regardless of the keys stored in the map, that you only want the `username` and `password` keys returned?

Correct

**Comment by difince** [comment]
Do we have credentials for Redis databases content  ? - I am not aware of ?

@AnthonyMBonafide The approach that you suggest together with @tingyuz (use of a base path such-as `/v1/secret/edgex/core-data`)  fits perfectly for edgex-go services, but not for edgex-mongo repo that need to handle all of them   - It will again need to create 10 instances of SecretConfig - but we can live with it :) 

I am not sure if I understand what bnevis-i meant 

> and give your service an additional special-case cross-cutting ability to read/write
/v1/secret/edgex/*/dbcredentials
so that each service can pick up its respective credential from its own area.
I think your service also needs a special superuser credential for its own use, correct?

What I am currently doing in edgex-mongo service - I use the common EdgeXFoundryCA.pem  + root token in order to read all the secrets within the vault. (this will change in a while  or it is already implemented ? ->  so that each service will have its own certificate and will be able to read only its own secrets  ) Following this, Yes, edgex-mongo will need permissions to read all secrets )  
Tell me if I am doing it in a wrong way and I need to update the logic ?

**Comment by tingyuz** [comment]
@difince I discussed with @mkbhanda regarding your special case of edgex-mongo. Our recommendation is to create a path for edgex-mongo within Vault and edgex-mongo will retrieve the credentials from that path. The synchronization of credentials between the paths within Vault will be taken care of internally. 

So in your case,  mongodb will have its own token, and your path will be /v1/secret/edgex/mongodb/{name-of-edgex-service}, and it will return JSON like this
{
 username: "admin",
 password: "password", 
}
Let us know if it works on your side.

**Comment by difince** [comment]
@tingyuz, I am Ok  with `creating a path for edgex-mongo within Vault and edgex-mongo will retrieve the credentials from that path`- thus be more secure by keeping the secrets separate per service ... but it will be a bit more to implement on "generating secrets" side

**Comment by AnthonyMBonafide** [comment]
@difince, You are correct there are no secrets for Redis so my example is not a good one.

For your case where you want to use one SecretConfig across multiple paths for different services you can use a base path of `/v1/secret/edgex` and use the `SecretClient` like so:

```
secretClient.GetValues("core-data/mongodb","username,"password")
secretClient.GetValues("core-metadata/mongodb","username,"password")
secretClient.GetValues("core-command/mongodb","username,"password")
```

This should resolve the issue of multiple `SecretConfig` instances for the purposes of paths. Would this idea work?

**Comment by difince** [comment]
@tingyuz  Where this mongo-token will be placed ? should i continue using EdgeXFoundryCA.pem ?

**Comment by difince** [comment]
@AnthonyMBonafide yes, you are correct..but it look all the credentials will be duplicated just for the edgex-mongo needs

**Comment by difince** [comment]
@tingyuz  Thank you for the clarification
